[build]
  base = "."
  command = "cd client && npm install && npm run build"
  publish = "client/dist"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./client/"

[build.environment]
  # Ignore TypeScript errors during build
  NETLIFY_USE_YARN = "false"
  NODE_VERSION = "18"
  NPM_FLAGS = "--prefix=./client --include=dev"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 