apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  database-url: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzLWRiOjU0MzIvbGVvbmV2ZXNfZGI=  # base64 encoded postgresql://postgres:postgres@postgres-db:5432/leoneves_db 